version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: 08:00
      timezone: Europe/Paris


  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/Docker"
    # Check for updates once a week
    schedule:
      interval: "weekly"
