services:
  mysql:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3316:3306"
    environment:
      - TZ=Europe/Paris
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/DB_ROOTPASSWORD
      #- MYSQL_ROOT_PASSWORD=changeIt # deprecated
      - MYSQL_DATABASE=jeedom
      - MYSQL_USER=jeedom
      #- MYSQL_PASSWORD=changeIt # deprecated
      - FILE__MYSQL_PASSWORD=/run/secrets/DB_PASSWORD
    secrets:
      - DB_ROOTPASSWORD
      - DB_PASSWORD
    volumes:
      - ./sqldata:/config
      - run_mysql:/run
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  web:
    image: edgd1er/jeedom-rpi:v4-latest
    restart: unless-stopped
    expose:
      - "22"
      - "80"
      - "443"
    ports:
      - "9180:80"
      - "9443:443"
    healthcheck:
      test: curl -s --fail http://localhost/here.html || exit 1
      interval: 1m30s
      retries: 3
      start_period: 40s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # only needed if you want to set your own certificate.
      #- ./cert.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      #- ./privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro
      - ./log:/var/log:rw
      - tmpfs_tmp:/tmp/
      - tmpfs_cache:/var/cache/
      - tmpfs_root_cache:/root/.cache
    environment:
      - TZ=Europe/Paris
      - JEEDOM_ENC_KEY= #<get key from /var/www/html/data/jeedom_encryption.key to keep database secrets consistent>
      - ROOT_PASSWD= # deprecated, replaced by secrets
      - DB_ROOTPASSWORD= # deprecated, replaced by secrets
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=jeedom
      - DB_USERNAME=jeedom
      - DB_PASSWORD= # deprecated, replaced by secrets
      - LOGS_TO_STDOUT=y
    secrets:
      - JEEDOM_ENCRYPTION_KEY
      - DB_ROOTPASSWORD
      - DB_PASSWORD
      - ROOT_PASSWD
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - mysql
secrets:
  JEEDOM_ENCRYPTION_KEY:
    file: ./JEEDOM_ENCRYPTION_KEY
  DB_ROOTPASSWORD:
    file: ./DB_ROOTPASSWORD
  DB_PASSWORD:
    file: ./DB_PASSWORD
  ROOT_PASSWD:
    file: ./ROOT_PASSWORD
volumes:
  tmpfs_root_cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmpfs_cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmpfs_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
  run_mysql:
    driver_opts:
      type: tmpfs
      device: tmpfs
