version: '3.5'
services:
  web:
    #image: edgd1er/jeedom-rpi:armhf-latest
    image: edgd1er/jeedom-rpi:v3-amd64-latest
    build:
      context: Docker
      dockerfile: Dockerfile
      args:
        DISTRO: "amd64-debian"
        #DISTRO: armv7hf-debian
        #VERSION: release
        VERSION: V4-stable
        aptcacher: 192.168.53.208
    #   devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0
    #   - "/dev/ttyACM0:/dev/ttyACM0"
    #   - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
      - "9080:80"
      - "9443:443"
    tmpfs:
      - /run:rw,size=10M
      - /tmp:rw,size=64M
      - /var/log:rw,size=32M
      - /var/www/html/log:rw,size=32M
    environment:
      - TZ=Europe/Paris
      - ROOT_PASSWORD=example
      - MYSQL_JEEDOM_HOST=mysql
      - MYSQL_JEEDOM_PORT=3306
      - MYSQL_JEEDOM_DBNAME=jeedom_test
      - MYSQL_JEEDOM_USERNAME=jeedom
      - MYSQL_JEEDOM_PASSWD=jeedom
    depends_on:
      - mysql
  mysql:
    image: mariadb/server
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: jeedom_test
      MYSQL_USER: jeedom
      MYSQL_PASSWORD: jeedom
    ports:
      - 3326:3306
    volumes:
      - ./Docker/allow_root_access.sql:/docker-entrypoint-initdb.d/allow_root_access.sql
      #- ./sqldata:/var/lib/mysql


