version: '3.5'
services:
  mysql:
    image: linuxserver/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: jeedom_test
      MYSQL_USER: jeedom
      MYSQL_PASSWORD: jeedom
    ports:
      - 3326:3306
    volumes:
      - ./Docker/allow_root_access.sql:/docker-entrypoint-initdb.d/allow_root_access.sql
      #- ./sqldata:/var/lib/mysql


