version: '3.5'
services:
  web:
    #image: edgd1er/jeedom-rpi:armhf-latest
    image: edgd1er/jeedom-rpi:amd86-latest
    build:
      dockerfile: Dockerfile
      args:
        DISTRO: "amd64-debian"
        #DISTRO: armv7hf-debian
        VERSION: release
        #version: v4-stable
        aptcacher: 192.168.53.208
    #   devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0
    #   - "/dev/ttyACM0:/dev/ttyACM0"
    #   - "/dev/ttyAMA0:/dev/ttyAMA0"
    depends_on:
      - mysql
  mysql:
    image: mariadb/server
    volumes:
      - ./Docker/allow_root_access.sql:/docker-entrypoint-initdb.d/allow_root_access.sql
      #- ./sqldata:/var/lib/mysql
