[program:cron]
command = /usr/sbin/cron -f -L4
user = root
autostart = true
autorestart = true
startretries = 3
logfile=/dev/null  ; Désactive les logs dans un fichier
stdout_logfile = /dev/stdout
stdout_logfile_backups = 0
stdout_logfile_maxbytes=0  ; Désactive la rotation des logs
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups = 0
;redirect_stderr = true
