[program:fail2ban]
command = /usr/bin/python3 /usr/bin/fail2ban-server  -fc /etc/fail2ban/
user = root
autostart = false
autorestart = false
logfile=/dev/null  ; Désactive les logs dans un fichier
stdout_logfile = /dev/stdout
stdout_logfile_backups = 0
stdout_logfile_maxbytes=0  ; Désactive la rotation des logs
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups = 0
;redirect_stderr = true
