name: check V3/V4 jeedom's version
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

env:
  J3_VERSION: 3.3.59
  J4_VERSION: 4.2.20

jobs:
  check-j4_version:
    runs-on: ubuntu-latest
    steps:
      - name: get J4 version
        id: getJ4version
        run: |
          ver=$(curl -s "https://raw.githubusercontent.com/jeedom/core/V4-stable/core/config/version")
          echo "latest built version: ${{ env.J4_VERSION }}, latest github version: ${ver}"
          if [[ ${{ env.J4_VERSION }} == ${ver} ]]; then exit 0; fi
          curl -s "https://raw.githubusercontent.com/jeedom/core/V4-stable/docs/fr_FR/changelog.md" | grep -A20 -P "## ${ver}" | sed '/^$/d' | head -10
          exit 1

  check-j3_version:
      runs-on: ubuntu-latest
      steps:
        - name: get J3 version
          id: getJ3version
          run: |
            ver=$(curl -s "https://raw.githubusercontent.com/jeedom/core/master/core/config/version")
            echo "latest built version: ${{ env.J3_VERSION }}, latest github version: ${ver}"
            if [[ ${{ env.J3_VERSION }} == ${ver} ]]; then exit 0; fi
            curl -s "https://raw.githubusercontent.com/jeedom/core/master/docs/fr_FR/changelog.md" | grep -A20 -P "${ver}" | sed '/^$/d' | head -10
            exit 1
