name: reusable worflow template Docker buildx armhf+amd64

permissions:
  security-events: write  # Required for CodeQL
  actions: read           # Required for some workflows
  contents: read          # Required for checkout

on:
  workflow_call:
    inputs:
      image_name:
        default: 'jeedom-rpi'
        description: 'image name'
        required: true
        type: string
      build_context:
        default: './Docker'
        required: false
        type: string
      build_dockerfile:
        description: 'Dockerfile'
        default: 'Dockerfile'
        type: string
      jdm_version:
        description: 'jeedom version'
        required: true
        default: 'develop'
        type: string
      tag:
        description: 'docker tag'
        required: true
        default: 'develop'
        type: string
      push:
        description: 'push to registry'
        required: true
        default: true
        type: boolean
      version:
        description: 'develop'
        default: 'develop'
        required: true
        type: string
      distro:
        description: 'base OS'
        required: true
        type: string
        default: "13-slim"

jobs:
  build-prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ inputs.image_name }}
      jdm_version: ${{ inputs.jdm_version }}
      build_context: ${{ inputs.build_context }}
      build_dockerfile: ${{ inputs.build_dockerfile }}
      distro: ${{ inputs.distro }}
      push: ${{ inputs.push }}
      tag: ${{ inputs.tag }}
      version: ${{ inputs.version }}
    steps:
      # FIXME: can't use env object in reusable workflow inputs: https://github.com/orgs/community/discussions/26671
      - run: |
          echo "Exposing env vars for reusable workflow"
          echo image_name: ${{ inputs.image_name }}
          echo jdm_version: ${{ inputs.jdm_version }}
          echo build_context: ${{ inputs.build_context }}
          echo build_dockerfile: ${{ inputs.build_dockerfile }}
          echo distro: ${{ inputs.distro }}
          echo push: ${{ inputs.push }}
          echo tag: ${{ inputs.tag }}
          echo version: ${{ inputs.version }}
          env

  github-builder:
      uses: docker/github-builder/.github/workflows/build.yml@v1
      needs: build-prepare
      permissions:
          contents: read # same as global permissions
          id-token: write # for signing attestation(s) with GitHub OIDC Token
          #packages: write # required to push to GHCR
      with:
          setup-qemu: true
          cache: true
          cache-scope: build
          fail-fast: true
          context: ${{ needs.build-prepare.outputs.build_context }}
          file: ${{ needs.build-prepare.outputs.build_dockerfile }}
          output: image
          build-args: |
            VERSION=${{ needs.build-prepare.outputs.version }}
            DISTRO=${{ needs.build-prepare.outputs.distro }}
            JDM_VERSION=${{ needs.build-prepare.outputs.jdm_version }}
            aptCacher: ''
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ needs.build-prepare.outputs.push == 'true' }}
          set-meta-labels: true
          meta-images: |
            ${{ github.repository_owner }}/${{ needs.build-prepare.outputs.image_name }}
          # ghcr.io/${{ github.repository_owner }}/jeedom-rpi
          meta-tags: |
            type=schedule,pattern=nightly
            type=raw,value=develop,enable=${{ github.event_name == 'push' }}
            type=raw,value=develop,enable=${{ github.event_name == 'workflow_dispatch' }}
            type=ref,event=tag
          meta-flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') }}
          # FIXME: GHCR does not support the referrers API and spams the registry with sha-tagged images when cosigned: https://github.com/docker/github-builder/issues/109
          sign: false
      secrets:
        registry-auths: |
          - registry: docker.io
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}

  inspect-security:
    runs-on: ubuntu-latest
    needs: [build-prepare, github-builder]
    permissions:
      contents: read # same as global permissions
      security-events: write
    steps:
      - uses: actions/checkout@v7
        with:
            fetch-depth: 0  # Important for CodeQL

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_USER }}/${{ inputs.image_name }}:${{ needs.build-prepare.outputs.tag }}

      - name: Docker Scout Quickview, recommandations and CVEs
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
          image: ${{ secrets.DOCKER_USER }}/${{ inputs.image_name }}:${{ needs.build-prepare.outputs.tag }}
          sarif-file: sarif.output.json # This will generate the SARIF file
          summary: true

      - name: Docker Scout SBOM
        uses: docker/scout-action@v1
        with:
          command: sbom
          image: ${{ secrets.DOCKER_USER }}/${{ inputs.image_name }}:${{ needs.build-prepare.outputs.tag }}
          output: sbom.json

      - name: Upload Docker Scout SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sarif.output.json

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USER }}/${{ inputs.image_name }}:${{ needs.build-prepare.outputs.tag }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
