name: Docker buildx armhf+amd64 v4 stable

on:
  workflow_dispatch:
    inputs:
      jdm_version:
        description: 'jeedom tag'
        required: true
        default: 'master'
        type: string
      version:
        description: 'branch'
        required: true
        default: 'master'
        type: string

#  push:
#    branches:
#      - master
#    paths-ignore:
#      - '.github/**'

jobs:
  build-v4:
    uses: ./.github/workflows/dockerimage-buildx-template.yml
    with:
      image_name: jeedom-rpi
      jdm_version: ${{ github.event_name == 'workflow' && inputs.jdm_version  || 'master'}}
      tag: ${{ github.event_name == 'workflow' && inputs.jdm_version  || 'master'}}
      version: ${{ github.event_name == 'workflow' && inputs.version  || 'master'}}
      #12 bookworm stable
      distro: 12-slim
      push: true
    secrets: inherit
