name: Docker Image CI armhf v4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image armhf 
      run: docker build -f Docker/Dockerfile.armhf --build-arg VERSION=release --build-arg DISTRO=armv7hf-debian -t edgd1er/jeedom-rpi:v3-armhf-latest ./Docker
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USER }}/jeedom-rpi:v3-armhf-latest
