name: Docker buildx armhf+amd64 v3

on:
  workflow_dispatch:
  #pull_request:
  #  branches:
  #    - master
  #  paths-ignore:
  #    - '.github/**'
  #push:
  #  branches:
  #    - master
  #    - gh_pb
  #  paths-ignore:
  #    - '.github/**'

env:
  IMAGE: jeedom-rpi
  TAG: v3-latest
  VERSION: release
  DISTRO: buster-slim
  aptCacher: ''

jobs:
  getenv:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          env
  build-images:
    uses: ./.github/workflows/dockerimage-buildx-template.yml
    with:
      image-name: jeedom-rpi
      build-context: './Docker'
      build-dockerfile: './Docker/Dockerfile.v3'
      jdm_version: latest
      tag: v3-latest
      version: release
      distro: buster-slim
      push: true
    secrets: inherit
