name: Docker buildx armhf+amd64 v4 develop

on:
  push:
    branches:
      - dev
  schedule:
    - cron: "15 20 * * 1"
  workflow_dispatch:
    inputs:
      jdm_version:
        description: 'master/release/develop'
        required: true
        default: 'develop'
        type: string
      image_name:
        description: 'image name'
        required: true
        default: 'jeedom-rpi'
        type: string
      distro:
        description: 'base image'
        required: true
        default: '13-slim'
        type: string
      push:
        description: 'push true/false'
        required: true
        default: true
        type: boolean

jobs:
  build-v4-develop:
    uses: ./.github/workflows/dockerimage-buildx-template.yml
    with:
      image_name: ${{ github.event_name == 'workflow' && inputs.image_name || 'jeedom-rpi'  }}
      jdm_version: ${{ github.event_name == 'workflow' && inputs.jdm_version  || 'develop'}}
      tag: ${{ github.event_name == 'workflow' && inputs.jdm_version  || 'develop'}}
      version: ${{ github.event_name == 'workflow' && inputs.jdm_version  || 'develop'}}
      distro: ${{ github.event_name == 'workflow' && inputs.distro || '13-slim' }}
      push: ${{ github.event_name == 'workflow' && inputs.push || 'true' == 'true' }}
    secrets: inherit
