name: lint jeedom-rpi dockerfile

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ./Docker/Dockerfile.buildx
