name: lint jeedom-rpi dockerfile

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Docker/Dockerfile
          failure-threshold: info               # name of threshold level (error | warning | info | style | ignore | none)
          format: json                          # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | gnu | codacy)
          no-color: false                       # true | false
          no-fail: false                        # true | false
          verbose: true                         #
